baseURL = 'https://jonharder.github.io/'
languageCode = 'en-us'
title = 'The Terminal Toolbelt'
theme = 'hello-friend-ng'
sectionPagesMenu = "main"

[params]
title = 'The Terminal Toolbelt'
Toc = true
themeColor = 'orange'

[languages.en.params.logo]
logoText = 'The Terminal Toolbelt'
logoHomeLink = '/'
