baseURL = 'https://jonharder.github.io/'
languageCode = 'en-us'
title = 'The Terminal Toolbelt'
theme = ['LoveIt', 'hugo-admonitions']
sectionPagesMenu = "main"

[params]
title = 'The Terminal Toolbelt'
description = "Filling your terminal toolbelt, one command at a time."
Toc = true

[params.author]
name = "Jon Harder"
email = "jonharder6@gmail.com"

[params.header.title]
name = "The Terminal Toolbelt"

[languages.en.params.logo]
logoText = 'The Terminal Toolbelt'
logoHomeLink = '/'

[params.page.share]
enable = false


[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "Tags"
    url = "/tags"

[markup]
  [markup.highlight]
    noClasses = false